kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeportal-api-access
rules:
- apiGroups: [""]
  resources: ["secrets","serviceaccounts","namespaces"]
  verbs: ["get","list","watch","create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get","list","watch","create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["bind"]
---
# This must be a CLusterRoleBinding, so that all namespaces
# can be modified
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeportal-api-access
roleRef:
  kind: ClusterRole
  name: kubeportal-api-access
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubeportal
