version: '3.3'

services:
  app:
    links:
      - api
    build:
      context: ./kubeportal-frontend
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    restart: always

  api:
    build:
      context: ./kubeportal-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always