version: '3.3'

services:
  app:
    links:
      - api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    restart: always

  api:
    build:
      context: ./kubeportal-dev-api
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    restart: always