FROM python:3.5-buster

COPY requirements.txt /tmp/

RUN apt-get update && \
    apt-get install -y gcc make libc-dev musl-dev libffi-dev libssl-dev libpcre3-dev && \
    pip install --no-cache-dir -r /tmp/requirements.txt uwsgi && \
    mkdir /code/ && \
    mkdir /data/

RUN mkdir /root/.kube
RUN mkdir /root/.minikube

COPY tmp/config     /root/.kube/config
COPY tmp/client.crt /root/.minikube/client.crt
COPY tmp/client.key /root/.minikube/client.key
COPY tmp/ca.crt     /root/.minikube/ca.crt

ENV KUBEPORTAL_STATIC_ROOT='/code/static-collected'
ENV KUBEPORTAL_STATICFILES_DIRS='/code/kubeportal/static'

EXPOSE 8000

CMD ["/bin/sh", "/code/deployment/docker/docker-entry-dev.sh"]
