openapi: 3.0.3
info:
  title: Kubeportal Backend API
  version: v1.5.0
paths:
  /api/:
    get:
      operationId: api_retrieve
      description: Retreive basic information needed to interact with the API.
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/v1.5.0/cluster/{id}/:
    get:
      operationId: api_v1.5.0_cluster_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this web application.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/v1.5.0/groups/:
    get:
      operationId: api_v1.5.0_groups_list
      description: API endpoint that allows for groups to queried
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PortalGroup'
          description: ''
  /api/v1.5.0/groups/{id}/:
    get:
      operationId: api_v1.5.0_groups_retrieve
      description: API endpoint that allows for groups to queried
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortalGroup'
          description: ''
  /api/v1.5.0/ingresses/:
    get:
      operationId: api_v1.5.0_ingresses_list
      description: |-
        View set to return the list of all host names used in Ingress definitions
        across all namespaces. This is used by the frontend for checking host names
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/v1.5.0/login/:
    post:
      operationId: api_v1.5.0_login_create
      description: |-
        Check the credentials and return the REST Token
        if the credentials are valid and authenticated.
        Calls Django Auth login method to register User ID
        in Django session framework

        Accept the following POST parameters: username, password
        Return the REST Framework Token Object's key.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1.5.0/login_google/:
    post:
      operationId: api_v1.5.0_login_google_create
      description: |-
        class used for social authentications
        example usage for facebook with access_token
        -------------
        from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter

        class FacebookLogin(SocialLoginView):
            adapter_class = FacebookOAuth2Adapter
        -------------

        example usage for facebook with code

        -------------
        from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
        from allauth.socialaccount.providers.oauth2.client import OAuth2Client

        class FacebookLogin(SocialLoginView):
            adapter_class = FacebookOAuth2Adapter
            client_class = OAuth2Client
            callback_url = 'localhost:8000'
        -------------
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialLogin'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SocialLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SocialLogin'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialLogin'
          description: ''
  /api/v1.5.0/logout/:
    post:
      operationId: api_v1.5.0_logout_create
      description: |-
        Calls Django logout method and delete the Token object
        assigned to the current User object.

        Accepts/Returns nothing.
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /api/v1.5.0/users/{id}/:
    get:
      operationId: api_v1.5.0_users_retrieve
      description: API endpoint that allows for users to queried
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: api_v1.5.0_users_update
      description: API endpoint that allows for users to queried
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: api_v1.5.0_users_partial_update
      description: API endpoint that allows for users to queried
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/v1.5.0/users/{user_pk}/deployments/:
    get:
      operationId: api_v1.5.0_users_deployments_list
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1.5.0_users_deployments_create
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/v1.5.0/users/{user_pk}/groups/:
    get:
      operationId: api_v1.5.0_users_groups_list
      description: API endpoint that allows for groups to queried
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PortalGroup'
          description: ''
  /api/v1.5.0/users/{user_pk}/groups/{id}/:
    get:
      operationId: api_v1.5.0_users_groups_retrieve
      description: API endpoint that allows for groups to queried
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortalGroup'
          description: ''
  /api/v1.5.0/users/{user_pk}/ingresses/:
    get:
      operationId: api_v1.5.0_users_ingresses_list
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1.5.0_users_ingresses_create
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/v1.5.0/users/{user_pk}/pods/:
    get:
      operationId: api_v1.5.0_users_pods_list
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1.5.0_users_pods_create
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/v1.5.0/users/{user_pk}/services/:
    get:
      operationId: api_v1.5.0_users_services_list
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_v1.5.0_users_services_create
      description: Generic base class for managing a particular Kubernetes resource
        type over the API.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
  /api/v1.5.0/users/{user_pk}/webapps/:
    get:
      operationId: api_v1.5.0_users_webapps_list
      description: API endpoint that allows for web application(s) to queried.
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebApplication'
          description: ''
  /api/v1.5.0/users/{user_pk}/webapps/{id}/:
    get:
      operationId: api_v1.5.0_users_webapps_retrieve
      description: API endpoint that allows for web application(s) to queried.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebApplication'
          description: ''
  /api/v1.5.0/webapps/:
    get:
      operationId: api_v1.5.0_webapps_list
      description: API endpoint that allows for web application(s) to queried.
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebApplication'
          description: ''
  /api/v1.5.0/webapps/{id}/:
    get:
      operationId: api_v1.5.0_webapps_retrieve
      description: API endpoint that allows for web application(s) to queried.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebApplication'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - th
          - tr
          - tt
          - udm
          - uk
          - ur
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Login:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
      - password
    PatchedUser:
      type: object
      properties:
        firstname:
          type: string
        name:
          type: string
        username:
          type: string
        primary_email:
          type: string
          format: email
        admin:
          type: boolean
        all_emails:
          type: array
          items: {}
        k8s_serviceaccount:
          type: string
        k8s_namespace:
          type: string
        k8s_token:
          type: string
    PortalGroup:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
      required:
      - name
    RestAuthDetail:
      type: object
      properties:
        detail:
          type: string
          readOnly: true
      required:
      - detail
    SocialLogin:
      type: object
      properties:
        access_token:
          type: string
        code:
          type: string
    User:
      type: object
      properties:
        firstname:
          type: string
        name:
          type: string
        username:
          type: string
        primary_email:
          type: string
          format: email
        admin:
          type: boolean
        all_emails:
          type: array
          items: {}
        k8s_serviceaccount:
          type: string
        k8s_namespace:
          type: string
        k8s_token:
          type: string
      required:
      - admin
      - all_emails
      - firstname
      - k8s_namespace
      - k8s_serviceaccount
      - k8s_token
      - name
      - primary_email
      - username
    WebApplication:
      type: object
      properties:
        link_name:
          type: string
          nullable: true
          description: The title of the link on the landing page. You can use the
            placeholders '{{namespace}}' and '{{serviceaccount}}'.
          maxLength: 100
        link_url:
          type: string
          format: uri
          nullable: true
          description: The URL of the link on the landing page. You can use the placeholders
            '{{namespace}}' and '{{serviceaccount}}'.
          maxLength: 200
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer
servers:
- url: '{server}/api/{version}'
  variables:
  - server:
      default: http://localhost:8000
  - version:
      default: v1.5.0
