# Generated by Django 2.1.7 on 2019-03-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2application',
            name='user',
        ),
        migrations.DeleteModel(
            name='OAuth2Application',
        ),
    ]
