# Generated by Django 2.2.10 on 2020-02-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0001_squashed_0009_auto_20200218_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetesserviceaccount',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='kubeportal.KubernetesNamespace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_account',
            field=models.ForeignKey(blank=True, help_text='Kubernetes namespace + service account of this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='kubeportal.KubernetesServiceAccount', verbose_name='Kubernetes account'),
        ),
    ]
