# Generated by Django 2.2.10 on 2020-03-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
        ('kubeportal', '0002_auto_20200224_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='WebApplication'
        ),
        migrations.AlterModelOptions(
            name='WebApplication',
            options={'verbose_name': 'web application'},
        ),
        migrations.RenameField(
            model_name='WebApplication',
            old_name='name',
            new_name='link_name'
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='link_name',
            field=models.CharField(blank=True, help_text="You can use the placeholders '{{namespace}}' and '{{serviceaccount}}' in the title.", max_length=100, null=True, verbose_name='Link title')
        ),
        migrations.AddField(
            model_name='WebApplication',
            name='name',
            field=models.CharField(max_length=100)
        ),
        migrations.RenameField(
            model_name='WebApplication',
            old_name='url',
            new_name='link_url'
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='link_url',
            field=models.URLField(blank=True, help_text="You can use the placeholders '{{namespace}}' and '{{serviceaccount}}' in the URL.", null=True, verbose_name='Link URL')
        ),
        migrations.AddField(
            model_name='webapplication',
            name='link_show',
            field=models.BooleanField(default=False, verbose_name='Show link on welcome page'),
        ),
        migrations.AddField(
            model_name='webapplication',
            name='oidc_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oidc_provider.Client', verbose_name='Client settings'),
        ),

        migrations.CreateModel(
            name='PortalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name for the user group')),
                ('auto_add', models.BooleanField(default=False, verbose_name='Add new users automatically to this group')),
                ('auto_admin', models.BooleanField(default=False, verbose_name='Users in this group are admins')),
                ('subauth', models.BooleanField(default=False, help_text='Enable sub-authentication with Kubernetes Bearer token.', verbose_name='Enable sub-authentication'))
            ],
            options={'verbose_name': 'User Group'},
        ),

        migrations.AddField(
            model_name='portalgroup',
            name='web_applications',
            field=models.ManyToManyField(blank=True, related_name='portal_groups', to='kubeportal.WebApplication', verbose_name='Web applications enabled for this user group'),
        ),
        migrations.AddField(
            model_name='user',
            name='portal_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='kubeportal.PortalGroup', verbose_name='Groups of the user'),
        ),
    ]

