# Generated by Django 2.1.7 on 2019-07-01 16:51

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0002_auto_20190301_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
