# Generated by Django 2.2.10 on 2020-03-26 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0003_auto_20200319_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='portal_groups', to=settings.AUTH_USER_MODEL, verbose_name='Members of the user group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='web_applications',
            field=models.ManyToManyField(blank=True, related_name='portal_groups', to='kubeportal.WebApplication', verbose_name='Web applications enabled for this user group'),
        ),
    ]
