# Generated by Django 2.2.10 on 2020-03-18 20:57

from django.db import migrations


def add_default_groups(apps, schema_editor):
    Group = apps.get_model('kubeportal', 'Group')
    all_users = Group()
    


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0003_group'),
    ]

    operations = [
        migrations.RunPython(add_default_groups),
    ]
