# Generated by Django 2.1.7 on 2019-08-08 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0003_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
