# Generated by Django 2.2.10 on 2020-03-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0003_auto_20200326_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalgroup',
            name='auto_add',
            field=models.BooleanField(default=False, help_text='Enabling this makes all new users automatically a member of this group. Existing users are not modified.', verbose_name='Add all new users'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='auto_admin',
            field=models.BooleanField(default=False, help_text='Enabling this gives all group members administrative access in the backend.', verbose_name='Administrators'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='subauth',
            field=models.BooleanField(default=False, help_text='Enabling this allows all group members the token-based sub-authentication with their Kubernetes credentials.', verbose_name='Enable sub-authentication'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='web_applications',
            field=models.ManyToManyField(blank=True, help_text='Group members can access the chosen web applications.', related_name='portal_groups', to='kubeportal.WebApplication', verbose_name='Web applications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='answered_by',
            field=models.ForeignKey(blank=True, help_text='Which user approved the cluster access for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portal_groups',
            field=models.ManyToManyField(blank=True, help_text='The user groups this account belongs to.', related_name='members', to='kubeportal.PortalGroup', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='link_name',
            field=models.CharField(blank=True, help_text="The title of the link on the landing page. You can use the placeholders '{{namespace}}' and '{{serviceaccount}}' in the title.", max_length=100, null=True, verbose_name='Link title'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='link_url',
            field=models.URLField(blank=True, help_text="The URL of the link on the landing page. You can use the placeholders '{{namespace}}' and '{{serviceaccount}}' in the URL.", null=True, verbose_name='Link URL'),
        ),
    ]
