# Generated by Django 2.2.10 on 2020-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0004_auto_20200326_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auto_add',
            field=models.BooleanField(default=False, verbose_name='Add new users automatically to this group'),
        ),
    ]
