# Generated by Django 2.2.10 on 2020-03-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0004_auto_20200330_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalgroup',
            name='auto_add_approved',
            field=models.BooleanField(default=False, help_text='Enabling this makes all newly approved Kubernetes users automatically a member of this group. Existing users are not modified. Users with cluster approval being removed stay in this group.', verbose_name='Auto-add approved users'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='auto_add_new',
            field=models.BooleanField(default=False, help_text='Enabling this makes all newly created users automatically a member of this group. Existing users are not modified.', verbose_name='Auto-add new users'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='can_admin',
            field=models.BooleanField(default=False, help_text='Enabling this allows members of this group to access the administrative backend.', verbose_name='Backend access'),
        ),
        migrations.AlterField(
            model_name='portalgroup',
            name='can_web_applications',
            field=models.ManyToManyField(blank=True, help_text='Web applications that are accessible for members of this group.', related_name='portal_groups', to='kubeportal.WebApplication', verbose_name='Web applications'),
        ),
    ]
