# Generated by Django 2.2.4 on 2019-08-13 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0005_auto_20190813_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approval_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
