# Generated by Django 2.2.10 on 2020-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0005_auto_20200401_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalgroup',
            name='auto_add_approved',
        ),
        migrations.RemoveField(
            model_name='portalgroup',
            name='auto_add_new',
        ),
        migrations.AddField(
            model_name='portalgroup',
            name='special_all_acounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalgroup',
            name='special_k8s_acounts',
            field=models.BooleanField(default=False),
        ),
    ]
