# Generated by Django 2.2.4 on 2019-09-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0006_auto_20190813_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='approved_by',
            new_name='answered_by',
        ),
    ]
