# Generated by Django 2.2.4 on 2019-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0007_auto_20190917_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.CharField(default='', help_text='Description on why this user needs cluster access. (150 characters)', max_length=150),
        ),
    ]
