# Generated by Django 2.2.10 on 2020-02-18 14:34

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0008_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.CharField(blank=True, default='', help_text='Description on why this user needs cluster access. (150 characters)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=django_fsm.FSMField(choices=[('not requested', 'not requested'), ('requested', 'requested'), ('rejected', 'rejected'), ('approved', 'approved')], default='not requested', help_text='The state of the cluster access approval workflow.', max_length=50, verbose_name='Cluster access'),
        ),
    ]
