# Generated by Django 2.2.16 on 2021-02-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='category',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('DOCUMENTATION', 'Documentation'), ('COMMUNICATION', 'Communication'), ('KUBERNETES', 'Kubernetes'), ('DEVELOPER', 'Developer'), ('DATABASE', 'Database'), ('MONITORING', 'Monitoring')], default='GENERIC', help_text='Category of the web application, impacts the visual representation on the frontend.', max_length=255),
        ),
    ]
