# Generated by Django 2.2.16 on 2021-02-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0011_webapplication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('NEW', 'not requested'), ('ACCESS_REQUESTED', 'requested'), ('ACCESS_REJECTED', 'rejected'), ('ACCESS_APPROVED', 'approved')], default='NEW', help_text='The state of the cluster access approval workflow.', max_length=100, verbose_name='Cluster access'),
        ),
    ]
